# This rule is not used by the project k8-kubebuilder-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the service.my.domain.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8-kubebuilder-operator
    app.kubernetes.io/managed-by: kustomize
  name: webapplication-editor-role
rules:
- apiGroups:
  - service.my.domain
  resources:
  - webapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service.my.domain
  resources:
  - webapplications/status
  verbs:
  - get
