# This rule is not used by the project k8-kubebuilder-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over service.my.domain.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8-kubebuilder-operator
    app.kubernetes.io/managed-by: kustomize
  name: webapplication-admin-role
rules:
- apiGroups:
  - service.my.domain
  resources:
  - webapplications
  verbs:
  - '*'
- apiGroups:
  - service.my.domain
  resources:
  - webapplications/status
  verbs:
  - get
