apiVersion: service.my.domain/v1
kind: WebApplication
metadata:
  labels:
    app.kubernetes.io/name: k8-kubebuilder-operator
    app.kubernetes.io/managed-by: kustomize
  name: webapplication-sample
spec:
  # TODO(user): Add fields here
